# -*- coding: utf-8 -*-
"""walmart.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RaD-KvQ9gdYjyKH7nHbX5yr1nbFyKe3h
"""

# Importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load Dataset
data=pd.read_csv("/content/Walmart.csv")

data.head()

# Check for missing values
data.isnull().sum()

data['Date'] = pd.to_datetime(data['Date'], dayfirst=True)

data['Year'] = data['Date'].dt.year
data['Month'] = data['Date'].dt.month
data['Week'] = data['Date'].dt.isocalendar().week.astype(int)

# Drop target + unnecessary columns
X = data.drop(['Weekly_Sales', 'Date'], axis=1)

# Target variable
y = data['Weekly_Sales']

print(X.head())
print(y.head())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, y_pred)
print("MAE:", mae)

from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=100, random_state=42)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

from sklearn.metrics import mean_absolute_error, mean_squared_error

mae_rf = mean_absolute_error(y_test, y_pred_rf)
mse_rf = mean_squared_error(y_test, y_pred_rf)

print("Random Forest MAE:", mae_rf)
print("Random Forest MSE:", mse_rf)

print("Linear Regression MAE:", mae_lr)
print("Random Forest MAE:", mae_rf)

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error

lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)

mae_lr = mean_absolute_error(y_test, y_pred)
mse_lr = mean_squared_error(y_test, y_pred)

print("Linear Regression MAE:", mae_lr)

from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=50, random_state=42)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

mae_rf = mean_absolute_error(y_test, y_pred_rf)
mse_rf = mean_squared_error(y_test, y_pred_rf)

print("Random Forest MAE:", mae_rf)

print("Linear Regression MAE:", mae_lr)
print("Random Forest MAE:", mae_rf)

import matplotlib.pyplot as plt

models = ['Linear Regression', 'Random Forest']
mae_values = [mae_lr, mae_rf]

plt.bar(models, mae_values)
plt.title("Model Comparison")
plt.xlabel("Models")
plt.ylabel("MAE")
plt.show()

from sklearn.metrics import r2_score

r2_lr = r2_score(y_test, y_pred)
print("Linear Regression R2:", r2_lr)

r2_rf = r2_score(y_test, y_pred_rf)
print("Random Forest R2:", r2_rf)

print("Linear Regression R2:", r2_lr)
print("Random Forest R2:", r2_rf)
